import { parseRolesYaml } from './access-grammar.js';

/**
 * Render a `roles.yaml` granting Admin to each email — the ONE renderer every
 * generated roles.yaml goes through (empty-remote seeding, the startup
 * top-up, and the break-glass recovery), so none of them can drift on
 * validation and each fails with the same actionable message.
 *
 * Each email is validated first, because a malformed one renders a file with
 * no working Admin — SILENTLY: a leading `#` turns the entry into a YAML
 * comment, an embedded newline breaks the list, an all-whitespace value
 * renders an empty entry. A bad ADMIN_EMAIL is operator error, and the
 * callers' fail-closed contracts want a message naming the fix instead of an
 * un-administrable knowledge base (or a write-validator rejection deep in the
 * recovery path).
 */
export function renderRolesYaml(
  adminEmails: readonly string[],
  /**
   * Provenance comment appended to the header. The seed/top-up default names
   * where the file came from; recovery passes `null` — claiming "generated at
   * KB-seed time" on a recovery-restored file would mislead whoever reads it.
   */
  provenance: string | null = 'Generated by the Doorway platform at KB-seed time from ADMIN_EMAIL.',
): string {
  const emails = adminEmails.map((raw) => {
    const email = raw.trim();
    if (email === '') {
      throw new Error('Seed admin email is empty — set ADMIN_EMAIL to a real address.');
    }
    if (email.startsWith('#')) {
      throw new Error(
        `Seed admin email ${JSON.stringify(raw)} starts with "#", which YAML reads as a comment — fix ADMIN_EMAIL.`,
      );
    }
    if (/\s/.test(email)) {
      throw new Error(
        `Seed admin email ${JSON.stringify(raw)} contains whitespace, which would corrupt roles.yaml — fix ADMIN_EMAIL.`,
      );
    }
    return email;
  });
  const lines = emails.map((e) => `    - ${e}`).join('\n');
  const text =
    '# Identity → role mapping for access control.\n' +
    '# Role names are case- and whitespace-insensitive. The `Admin` role is special:\n' +
    '# only Admins may edit this file, and at least one Admin must always exist.\n' +
    (provenance !== null ? `#\n# ${provenance}\n` : '') +
    'roles:\n' +
    '  Admin:\n' +
    `${lines}\n`;
  // Validate by PARSING with the real access parser, not by re-implementing
  // its email grammar: whatever the parser would reject (a `<Name <email>`
  // shape, a non-email string, tomorrow's new rule) must fail here, before an
  // un-administrable roles.yaml gets committed. The checks above exist only
  // to give the common mistakes sharper messages.
  const parsed = parseRolesYaml(text);
  if (!parsed.ok) {
    throw new Error(
      `Generated roles.yaml from ADMIN_EMAIL would not parse — fix the configured address(es). ` +
        parsed.errors.join('; '),
    );
  }
  return text;
}
