/**
 * In-memory mapping from MCP session id → { userId, tokenId }. Each entry
 * represents one MCP client connection's worth of state: the Doorway user the
 * Bearer token resolved to at `initialize`, and the connection-key id for
 * metering. Conversation continuity is the caller's own (a continuity-aware
 * tool like `ask` returns its `sessionId` in the result and the caller echoes
 * it back); thread/workspace bookkeeping lives on the REST tool surface.
 *
 * Eviction is lazy: each `get` / `touch` sweeps idle entries before the
 * lookup, and `put` enforces the size cap before insert. No background
 * timer — keeps the store cheap to construct and avoids leaking a setInterval
 * handle in tests.
 *
 * Single-replica only. If we add a second backend instance later, sessions
 * need to be persisted (see docs/mcp-remote-access.md → "Out of scope"). The
 * MCP protocol tolerates this — a 404 on an unknown session id is a defined
 * response, and clients re-initialize.
 */

export interface McpSession {
  sessionId: string;
  userId: string;
  /**
   * The connection-key id this session authenticated with, or null when the
   * session was opened with a browser JWT (no connection key). Captured at
   * `initialize` so every `ask_doorway_agent` call in the session can be metered
   * against that key's daily token cap.
   */
  tokenId: string | null;
  createdAt: number;
  lastTouchedAt: number;
}

export interface McpSessionStoreOptions {
  /** Drop sessions idle for longer than this. Default: 4 hours. */
  idleTtlMs?: number;
  /** Hard cap on simultaneous live sessions. Oldest-touched evicted first. */
  maxSessions?: number;
  /** Override `Date.now` — injected only by tests. */
  now?: () => number;
}

const DEFAULT_IDLE_TTL_MS = 4 * 60 * 60 * 1000;
const DEFAULT_MAX_SESSIONS = 5000;

export class McpSessionStore {
  private readonly sessions = new Map<string, McpSession>();
  private readonly idleTtlMs: number;
  private readonly maxSessions: number;
  private readonly now: () => number;
  // Subscribers notified whenever a session is dropped by the store itself
  // (idle TTL sweep or size-cap eviction). NOT fired by explicit `delete()` —
  // the caller of `delete` already knows the session is gone, and the route
  // layer uses `delete` *because* it's already cleaning up.
  //
  // Callbacks are invoked synchronously; long-running cleanup (e.g.
  // `transport.close()`) should be fire-and-forget so a slow listener can't
  // block the next eviction.
  private readonly evictListeners = new Set<(sessionId: string) => void>();

  constructor(opts: McpSessionStoreOptions = {}) {
    this.idleTtlMs = opts.idleTtlMs ?? DEFAULT_IDLE_TTL_MS;
    this.maxSessions = opts.maxSessions ?? DEFAULT_MAX_SESSIONS;
    this.now = opts.now ?? Date.now;
  }

  /**
   * Subscribe to eviction events. Returns an unsubscribe function so callers
   * can clean up in test teardown. The route layer uses this to drop the
   * transport-state entry in its `active` map and close the underlying SDK
   * transport when the store decides a session has aged out.
   */
  onEvict(listener: (sessionId: string) => void): () => void {
    this.evictListeners.add(listener);
    return () => {
      this.evictListeners.delete(listener);
    };
  }

  /**
   * Register a fresh MCP session. Caller supplies the id (generated by the
   * SDK's transport). Evicts the oldest-touched session if the cap is hit
   * — better than refusing the connection, since a wedged old session is
   * the most likely cause of a full table.
   */
  create(sessionId: string, userId: string, tokenId: string | null = null): McpSession {
    this.sweep();
    if (this.sessions.size >= this.maxSessions) {
      this.evictOldest();
    }
    const now = this.now();
    const session: McpSession = {
      sessionId,
      userId,
      tokenId,
      createdAt: now,
      lastTouchedAt: now,
    };
    this.sessions.set(sessionId, session);
    return session;
  }

  /**
   * Look up a session and bump its `lastTouchedAt`. Returns null when the
   * session is unknown or has aged out. Sweep runs first so an aged entry
   * is collected, not silently revived.
   */
  get(sessionId: string): McpSession | null {
    this.sweep();
    const session = this.sessions.get(sessionId);
    if (!session) return null;
    session.lastTouchedAt = this.now();
    return session;
  }

  delete(sessionId: string): void {
    this.sessions.delete(sessionId);
  }

  /** Visible size; useful for diagnostics. Does not sweep. */
  size(): number {
    return this.sessions.size;
  }

  private sweep(): void {
    const cutoff = this.now() - this.idleTtlMs;
    for (const [id, s] of this.sessions) {
      if (s.lastTouchedAt < cutoff) {
        this.sessions.delete(id);
        this.emitEviction(id);
      }
    }
  }

  private evictOldest(): void {
    let oldestId: string | null = null;
    let oldestTouched = Infinity;
    for (const [id, s] of this.sessions) {
      if (s.lastTouchedAt < oldestTouched) {
        oldestTouched = s.lastTouchedAt;
        oldestId = id;
      }
    }
    if (oldestId) {
      this.sessions.delete(oldestId);
      this.emitEviction(oldestId);
    }
  }

  private emitEviction(sessionId: string): void {
    for (const listener of this.evictListeners) {
      try {
        listener(sessionId);
      } catch (err) {
        // A misbehaving listener must not stop the sweep from finishing —
        // otherwise one bad subscriber would block the rest of the eviction
        // pass and leak more sessions.
        console.warn('[mcp-session-store] eviction listener threw:', err);
      }
    }
  }
}
